### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by nosnivel** [keneanung/Bashing#22]
1. I am getting the following message:

keneanung: Something went completely wrong: You are using an unknown system ('prythe'). Please use 'kconfig bashing system <name>' to correct this.

But when I use 

kconfig bashing system goop

It returns:

keneanung: System not changed as 'goop' is unknown.

Also....

When I change rooms, it is not updating my target, so I am not switching.

**Comment by keneanung** [comment]
There are only 3 options that are accepted by the system settings out of the box:
1. `auto`: Tries to recognize whether you use svo or wundersys automatically and uses that option
2. `svo`: Uses svo as underlying queueing system
3. `wundersys`: Uses wundersys as queueing system

If you have your own system and want to use the bashing script with it, you will need to add a table with a certain to the keneanung.bashing.systems table. I tried to document the structure at https://github.com/keneanung/Bashing#support-for-other-systems. You can also add other fields to the table of course, but those functions are the interface used by the Bashing script. The svo and wundersys tables in the script are examples you can use as templates.

As for the not switching targets... Make sure the script is enabled (`kconfig bashing toggle`) and that gmcp is enabled.

**Comment by keneanung** [comment]
Any updates or are the issues solved?

**Comment by keneanung** [comment]
Feel free to reopen, if the issue was not solved :smile:
